import re
from pathlib import Path

from highland.runtime.events import EventType

ROOT = Path(__file__).parents[2]
GUIDE = ROOT / "docs" / "LEARNING_PATH.md"


def test_learning_path_covers_all_guided_exercises() -> None:
    guide = GUIDE.read_text(encoding="utf-8")

    for heading in (
        "## 1. Discover",
        "## 2. Create",
        "## 3. Approve",
        "## 4. Automate",
        "## Scripted versus real mode",
    ):
        assert heading in guide
    for path in (
        "tests/acceptance/test_meeting_preparation.py",
        "tests/integration/test_artifact_model_flow.py",
        "tests/acceptance/test_deployment_investigation.py",
        "tests/acceptance/test_workflow_builder.py",
        "tests/acceptance/test_weekly_customer_health.py",
    ):
        assert path in guide
        assert (ROOT / path).is_file()


def test_code_map_names_every_durable_event_and_existing_module() -> None:
    guide = GUIDE.read_text(encoding="utf-8")

    for event_type in EventType:
        assert f"`{event_type.value}`" in guide
    for relative in set(re.findall(r"`(src/[^`]+\.py)`", guide)):
        assert (ROOT / relative).is_file(), relative


def test_guide_labels_scripted_output_and_live_cost_boundary() -> None:
    guide = GUIDE.read_text(encoding="utf-8")
    normalized = " ".join(guide.split())

    assert "not answers generated by a language model" in normalized
    assert "HIGHLAND_MODEL_BACKEND=cohere COHERE_API_KEY=..." in guide
    assert "potentially billable" in guide
